

let mock = [{
    id: 1,
    name: 'Captain America',
    time: '2hr 4min',
    good: false,
    ironman: false,
    captainamerica: true,
    thor: false,
    blackwidow: false,
    hawkeye: false,
    drstrange: false,
    blackpanther: false,
    hulk: false,
    antman: false,
    captainmarvel: false,
    phase: 1,
    image: 'captain-america.jpg'
},
{
    id: 2,
    name: 'Captain America 2',
    time: '2hr 16min',
    good: true,
    ironman: false,
    captainamerica: true,
    thor: false,
    blackwidow: true,
    hawkeye: false,
    drstrange: false,
    blackpanther: false,
    hulk: false,
    antman: false,
    captainmarvel: false,
    phase: 2,
    image: 'captain-america-2.jpg'
},
{
    id: 3,
    name: 'Captain America 3',
    time: '2hr 27min',
    good: true,
    ironman: true,
    captainamerica: true,
    thor: false,
    blackwidow: true,
    hawkeye: true,
    drstrange: false,
    blackpanther: true,
    hulk: false,
    antman: true,
    captainmarvel: false,
    phase: 3,
    image: 'captain-america-3.jpg'
},
{
    id: 4,
    name: 'Iron Man',
    time: '2hr 6min',
    good: true,
    ironman: true,
    captainamerica: false,
    thor: false,
    blackwidow: false,
    hawkeye: false,
    drstrange: false,
    blackpanther: false,
    hulk: false,
    antman: false,
    captainmarvel: false,
    phase: 1,
    image: 'iron-man.jpg'
},
{
    id: 5,
    name: 'Iron man 2',
    time: '2hr 4min',
    good: false,
    ironman: true,
    captainamerica: false,
    thor: false,
    blackwidow: true,
    hawkeye: false,
    drstrange: false,
    blackpanther: false,
    hulk: false,
    antman: false,
    captainmarvel: false,
    phase: 1,
    image: 'iron-man-2.jpg'
},
{
    id: 6,
    name: 'Iron Man 3',
    time: '2hr 10min',
    good: false,
    ironman: true,
    captainamerica: false,
    thor: false,
    blackwidow: false,
    hawkeye: false,
    drstrange: false,
    blackpanther: false,
    hulk: false,
    antman: false,
    captainmarvel: false,
    phase: 2,
    image: 'iron-man-3.jpg'
},
{
    id: 7,
    name: 'Thor',
    time: '1hr 55min',
    good: true,
    ironman: false,
    captainamerica: false,
    thor: true,
    blackwidow: false,
    hawkeye: false,
    drstrange: false,
    blackpanther: false,
    hulk: false,
    antman: false,
    captainmarvel: false,
    phase: 1,
    image: 'thor.jpg'
},
{
    id: 8,
    name: 'Thor 2',
    time: '1hr 52min',
    good: false,
    ironman: false,
    captainamerica: false,
    thor: true,
    blackwidow: false,
    hawkeye: false,
    drstrange: false,
    blackpanther: false,
    hulk: false,
    antman: false,
    captainmarvel: false,
    phase: 2,
    image: 'thor-2.jpg'
},
{
    id: 9,
    name: 'Thor 3',
    time: '2hr 10min',
    good: true,
    ironman: false,
    captainamerica: false,
    thor: true,
    blackwidow: false,
    hawkeye: false,
    drstrange: true,
    blackpanther: false,
    hulk: true,
    antman: false,
    captainmarvel: false,
    phase: 3,
    image: 'thor-3.jpg'
},
{
    id: 10,
    name: 'Ant Man',
    time: '1hr 57min',
    good: true,
    ironman: false,
    captainamerica: false,
    thor: false,
    blackwidow: false,
    hawkeye: false,
    drstrange: false,
    blackpanther: false,
    hulk: false,
    antman: true,
    captainmarvel: false,
    phase: 2,
    image: 'ant-man.jpg'
},
{
    id: 11,
    name: 'Ant Man 2',
    time: '1hr 58min',
    good: false,
    ironman: false,
    captainamerica: false,
    thor: false,
    blackwidow: false,
    hawkeye: false,
    drstrange: false,
    blackpanther: false,
    hulk: false,
    antman: true,
    captainmarvel: false,
    phase: 3,
    image: 'ant-man-2.jpg'
},
{
    id: 12,
    name: 'Avengers',
    time: '2hr 23min',
    good: true,
    ironman: true,
    captainamerica: true,
    thor: true,
    blackwidow: true,
    hawkeye: true,
    drstrange: false,
    blackpanther: false,
    hulk: true,
    antman: false,
    captainmarvel: false,
    phase: 1,
    image: 'avengers.jpg'
},
{
    id: 13,
    name: 'Avengers 2',
    time: '2hr 21min',
    good: false,
    ironman: true,
    captainamerica: true,
    thor: true,
    blackwidow: true,
    hawkeye: true,
    drstrange: false,
    blackpanther: false,
    hulk: true,
    antman: false,
    captainmarvel: false,
    phase: 2,
    image: 'avengers-2.jpg'
},
{
    id: 14,
    name: 'Avengers 3',
    time: '3hr 1min',
    good: true,
    ironman: true,
    captainamerica: true,
    thor: true,
    blackwidow: true,
    hawkeye: true,
    drstrange: true,
    blackpanther: true,
    hulk: true,
    antman: true,
    captainmarvel: false,
    phase: 3,
    image: 'avengers-3.jpg'
},
{
    id: 15,
    name: 'Avengers 4',
    time: '3hr 1min',
    good: true,
    ironman: true,
    captainamerica: true,
    thor: true,
    blackwidow: true,
    hawkeye: true,
    drstrange: true,
    blackpanther: true,
    hulk: true,
    antman: true,
    captainmarvel: true,
    phase: 3,
    image: 'avengers-4.jpg'
},
{
    id: 16,
    name: 'Black Panther',
    time: '2hr 14min',
        good: false,
        ironman: false,
        captainamerica: false,
        thor: false,
        blackwidow: false,
        hawkeye: false,
        drstrange: false,
        blackpanther: true,
        hulk: false,
        antman: false,
        captainmarvel: false,
        phase: 3,
        image: 'black-panther.jpg'
    },
    {
        id: 17,
        name: 'Dr Strange',
        time: '1hr 55min',
        good: true,
        ironman: false,
        captainamerica: false,
        thor: false,
        blackwidow: false,
        hawkeye: false,
        drstrange: true,
        blackpanther: false,
        hulk: false,
        antman: false,
        captainmarvel: false,
        phase: 3,
        image: 'dr-strange.jpeg'
    },

]

export default mock;
